version: 2

jobs:
    test:
        working_directory: ~/wp-plugin

        docker:
            - image: circleci/php:7.0.33

        steps:
            - checkout

            - restore_cache:
                name: 'dependencies | restore cache'
                keys:
                    - dependencies-composer-{{ checksum "composer.lock" }}

            - run:
                name: 'dependencies | install composer'
                command: 'composer install --prefer-source --no-interaction'

            - save_cache:
                name: 'dependencies | save cache'
                key: dependencies-composer-{{ checksum "composer.lock" }}
                paths:
                    - vendor

            - restore_cache:
                name: 'dependencies | WP plugin: restore cache'
                keys:
                    - dependencies-composer-{{ checksum "app/composer.lock" }}

            - run:
                name: 'dependencies | WP plugin: install composer'
                command: 'cd app && composer install --prefer-source --no-interaction'

            - save_cache:
                name: 'dependencies | WP plugin: save cache'
                key: dependencies-composer-{{ checksum "app/composer.lock" }}
                paths:
                    - app/vendor

            - run:
                name: 'tests | WP plugin: PHP Code Sniffer'
                command: 'composer phpcs'

            - run:
                name: 'tests | WP plugin: PHPStan'
                command: 'composer phpstan'

workflows:
    version: 2
    build_and_test:
        jobs:
            - test
